# Generated by Django 3.2.15 on 2022-08-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://thumbs.dreamstime.com/b/restaurant-placeholder-vector-icon-restaurant-placeholder-vector-icon-filled-flat-sign-mobile-concept-web-design-cafe-map-141927414.jpg', max_length=500),
        ),
    ]
